### ISSUE TITLE
Cannot run tests

### ISSUE THREAD

**Issue by vismate** [AMIOL7/ELME#28] opened 2022-11-14 23:01 UTC
When trying to run tests written by @bgdxqi I get the following error: 

```
> Task :app:compileTestJava FAILED
ELME/app/src/test/java/ELME/AppTest.java:10: error: cannot find symbol
import static org.junit.Assert.assertEquals;
                       ^
  symbol:   class Assert
  location: package org.junit
/ELME/app/src/test/java/ELME/AppTest.java:10: error: static import only from classes and interfaces
import static org.junit.Assert.assertEquals;
^
ELME/app/src/test/java/ELME/AppTest.java:11: error: cannot find symbol
import static org.junit.Assert.assertFalse;
                       ^
  symbol:   class Assert
  location: package org.junit
ELME/app/src/test/java/ELME/AppTest.java:11: error: static import only from classes and interfaces
import static org.junit.Assert.assertFalse;
^
ELME/app/src/test/java/ELME/AppTest.java:12: error: cannot find symbol
import static org.junit.Assert.assertTrue;
                       ^
  symbol:   class Assert
  location: package org.junit
ELME/app/src/test/java/ELME/AppTest.java:12: error: static import only from classes and interfaces
import static org.junit.Assert.assertTrue;
^
6 errors
```

I've tried installing junit with my package manager and I also tried some suggestions from stackoverflow. Nothing seemed to work. @bgdxqi how did you manage to run the tests? Do you have any recommendations?

**Comment by AMIOL7** [comment] 2022-11-15 05:33
Perhaps, the issue is in the version of JUnit. If I remember correctly, last semester I had problems using JUnit 5 in Netbeans. Have you tried using version 4?

**Comment by AMIOL7** [comment] 2022-11-15 06:35
@vismate Also, JUnit 5 has different package structure

**Comment by vismate** [comment] 2022-11-15 07:25
I think I have JUnit 4 installed, although I don't even think its detected. Also, which version of JUnit does our github action use?

**Comment by AMIOL7** [comment] 2022-11-15 08:21
@vismate I am not sure which version it pulls. It just downloads gradle 7.4 and executes gradlew test

**Comment by AMIOL7** [comment] 2022-11-15 08:27
I think we have JUnit version 5.8.1
<img width="318" alt="image" src="https://user-images.githubusercontent.com/114759784/201868146-be16a762-9ec0-4839-a146-a92f31031327.png">

**Comment by AMIOL7** [comment] 2022-11-15 08:31
@vismate  Try putting this is build file in dependencies: testImplementation('junit:junit:4.13')

**Comment by vismate** [comment] 2022-11-15 08:36
Thanks, this worked. I tried the same thing with an other version of JUnit that didn't work. Should I commit this change to the repo too?

**Comment by AMIOL7** [comment] 2022-11-15 08:37
yes

**Comment by AMIOL7** [comment] 2022-11-15 08:38
Which version of JUnit did you try before?

**Comment by vismate** [comment] 2022-11-15 08:43
> Which version of JUnit did you try before?

5.something

**Comment by vismate** [comment] 2022-11-15 10:19
I've figured everything out:
@bgdxqi imported assertions from JUnit (presumably 4.*) and ignored the already imported ```junit.jupiter.api.Assertions.* ```  in the ```AppTest.java``` file. Our gradle project was already set up to use ```org.junit.jupiter:junit-jupiter:5.8.1``` as a testing environment. In my following commits I'll use ```junit.jupiter```, as it is officially (or at least better) supported by gradle.

**Comment by bgdxqi** [comment] 2022-11-15 14:14
Everything worked just fine on my end. Haven't run into a single issue. (If we don't count the failed test cases, caused by logical issues in the model , ofc. Which were fixed by now.)

**Comment by bgdxqi** [comment] 2022-11-15 14:16
I took it as you've "figured everything out", so we might close it as well for now.

**Closed as completed by bgdxqi** 2022-11-15 14:16 UTC
Labels: help wanted
